### ISSUE TITLE
support to style

### ISSUE THREAD

**Issue by wesleytoshio** [tal-tech/flutter_intro#25]
it would be very interesting to be able to stylize the texts and buttons of the introduction to maintain the real identity of the application.

Loving this package 😍

**Comment by hellohejinyu** [comment]
https://github.com/tal-tech/flutter_intro#custom-widgetbuilder-method, In order to keep the code concise, the library provides this method to completely customize the content for the user.The example link https://github.com/tal-tech/flutter_intro/blob/64f96998634f72b0935089afd215281b42bcfd9b/example/lib/main.dart#L135

**Comment by wesleytoshio** [comment]
Thanks
